services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  manager:
    image: mymanager
    ports:
      - "8080:8080"
    environment:
      spring.rabbitmq.host: rabbitmq
    depends_on:
      - rabbitmq
  worker:
    image: myworker
    environment:
      spring.rabbitmq.host: rabbitmq
    depends_on:
      - rabbitmq
